# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'emc.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_emcform(object):
    def setupUi(self, emcform):
        emcform.setObjectName("emcform")
        emcform.resize(433, 357)
        self.cb_com = QtWidgets.QComboBox(emcform)
        self.cb_com.setGeometry(QtCore.QRect(3, 11, 69, 20))
        self.cb_com.setObjectName("cb_com")
        self.btn_serch = QtWidgets.QPushButton(emcform)
        self.btn_serch.setGeometry(QtCore.QRect(90, 10, 75, 23))
        self.btn_serch.setObjectName("btn_serch")
        self.btn_open = QtWidgets.QPushButton(emcform)
        self.btn_open.setGeometry(QtCore.QRect(180, 10, 75, 23))
        self.btn_open.setObjectName("btn_open")
        self.btn_send = QtWidgets.QPushButton(emcform)
        self.btn_send.setGeometry(QtCore.QRect(270, 10, 75, 23))
        self.btn_send.setObjectName("btn_send")
        self.btn_sql = QtWidgets.QPushButton(emcform)
        self.btn_sql.setGeometry(QtCore.QRect(350, 10, 75, 23))
        self.btn_sql.setObjectName("btn_sql")
        self.label = QtWidgets.QLabel(emcform)
        self.label.setGeometry(QtCore.QRect(2, 43, 54, 16))
        self.label.setObjectName("label")
        self.txt_emmc = QtWidgets.QLineEdit(emcform)
        self.txt_emmc.setGeometry(QtCore.QRect(53, 43, 40, 20))
        self.txt_emmc.setReadOnly(True)
        self.txt_emmc.setObjectName("txt_emmc")
        self.btn_emmc = QtWidgets.QPushButton(emcform)
        self.btn_emmc.setGeometry(QtCore.QRect(150, 43, 60, 23))
        self.btn_emmc.setObjectName("btn_emmc")
        self.label_2 = QtWidgets.QLabel(emcform)
        self.label_2.setGeometry(QtCore.QRect(2, 69, 54, 16))
        self.label_2.setObjectName("label_2")
        self.txt_gf = QtWidgets.QLineEdit(emcform)
        self.txt_gf.setGeometry(QtCore.QRect(53, 69, 40, 20))
        self.txt_gf.setReadOnly(True)
        self.txt_gf.setObjectName("txt_gf")
        self.label_3 = QtWidgets.QLabel(emcform)
        self.label_3.setGeometry(QtCore.QRect(2, 95, 54, 16))
        self.label_3.setObjectName("label_3")
        self.txt_epprom = QtWidgets.QLineEdit(emcform)
        self.txt_epprom.setGeometry(QtCore.QRect(53, 95, 40, 20))
        self.txt_epprom.setReadOnly(True)
        self.txt_epprom.setObjectName("txt_epprom")
        self.label_4 = QtWidgets.QLabel(emcform)
        self.label_4.setGeometry(QtCore.QRect(2, 121, 54, 16))
        self.label_4.setObjectName("label_4")
        self.txt_c0 = QtWidgets.QLineEdit(emcform)
        self.txt_c0.setGeometry(QtCore.QRect(53, 121, 40, 20))
        self.txt_c0.setReadOnly(True)
        self.txt_c0.setObjectName("txt_c0")
        self.label_5 = QtWidgets.QLabel(emcform)
        self.label_5.setGeometry(QtCore.QRect(2, 147, 54, 16))
        self.label_5.setObjectName("label_5")
        self.txt_c1 = QtWidgets.QLineEdit(emcform)
        self.txt_c1.setGeometry(QtCore.QRect(53, 147, 40, 20))
        self.txt_c1.setReadOnly(True)
        self.txt_c1.setObjectName("txt_c1")
        self.btn_gf = QtWidgets.QPushButton(emcform)
        self.btn_gf.setGeometry(QtCore.QRect(150, 69, 60, 23))
        self.btn_gf.setObjectName("btn_gf")
        self.btn_epprom = QtWidgets.QPushButton(emcform)
        self.btn_epprom.setGeometry(QtCore.QRect(150, 95, 60, 23))
        self.btn_epprom.setObjectName("btn_epprom")
        self.btn_c0 = QtWidgets.QPushButton(emcform)
        self.btn_c0.setGeometry(QtCore.QRect(150, 121, 60, 23))
        self.btn_c0.setObjectName("btn_c0")
        self.btn_can1 = QtWidgets.QPushButton(emcform)
        self.btn_can1.setGeometry(QtCore.QRect(150, 147, 60, 23))
        self.btn_can1.setObjectName("btn_can1")
        self.btn_can2 = QtWidgets.QPushButton(emcform)
        self.btn_can2.setGeometry(QtCore.QRect(370, 69, 60, 23))
        self.btn_can2.setObjectName("btn_can2")
        self.btn_dtu = QtWidgets.QPushButton(emcform)
        self.btn_dtu.setGeometry(QtCore.QRect(370, 95, 60, 23))
        self.btn_dtu.setObjectName("btn_dtu")
        self.btn_login = QtWidgets.QPushButton(emcform)
        self.btn_login.setGeometry(QtCore.QRect(370, 121, 60, 23))
        self.btn_login.setObjectName("btn_login")
        self.btn_l99m = QtWidgets.QPushButton(emcform)
        self.btn_l99m.setGeometry(QtCore.QRect(370, 147, 60, 23))
        self.btn_l99m.setObjectName("btn_l99m")
        self.btn_port = QtWidgets.QPushButton(emcform)
        self.btn_port.setGeometry(QtCore.QRect(151, 201, 60, 23))
        self.btn_port.setObjectName("btn_port")
        self.txt_all = QtWidgets.QTextBrowser(emcform)
        self.txt_all.setGeometry(QtCore.QRect(2, 230, 421, 121))
        self.txt_all.setObjectName("txt_all")
        self.btn_fill = QtWidgets.QPushButton(emcform)
        self.btn_fill.setGeometry(QtCore.QRect(220, 201, 60, 23))
        self.btn_fill.setObjectName("btn_fill")
        self.label_8 = QtWidgets.QLabel(emcform)
        self.label_8.setGeometry(QtCore.QRect(220, 95, 54, 16))
        self.label_8.setObjectName("label_8")
        self.txt_ec20 = QtWidgets.QLineEdit(emcform)
        self.txt_ec20.setGeometry(QtCore.QRect(270, 95, 40, 20))
        self.txt_ec20.setReadOnly(True)
        self.txt_ec20.setObjectName("txt_ec20")
        self.txt_l99m = QtWidgets.QLineEdit(emcform)
        self.txt_l99m.setGeometry(QtCore.QRect(270, 147, 40, 20))
        self.txt_l99m.setReadOnly(True)
        self.txt_l99m.setObjectName("txt_l99m")
        self.label_10 = QtWidgets.QLabel(emcform)
        self.label_10.setGeometry(QtCore.QRect(220, 147, 54, 16))
        self.label_10.setObjectName("label_10")
        self.txt_mcu = QtWidgets.QLineEdit(emcform)
        self.txt_mcu.setGeometry(QtCore.QRect(270, 43, 40, 20))
        self.txt_mcu.setReadOnly(True)
        self.txt_mcu.setObjectName("txt_mcu")
        self.label_7 = QtWidgets.QLabel(emcform)
        self.label_7.setGeometry(QtCore.QRect(220, 69, 54, 16))
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(emcform)
        self.label_6.setGeometry(QtCore.QRect(220, 43, 54, 16))
        self.label_6.setObjectName("label_6")
        self.txt_c2 = QtWidgets.QLineEdit(emcform)
        self.txt_c2.setGeometry(QtCore.QRect(270, 69, 40, 20))
        self.txt_c2.setReadOnly(True)
        self.txt_c2.setObjectName("txt_c2")
        self.label_9 = QtWidgets.QLabel(emcform)
        self.label_9.setGeometry(QtCore.QRect(220, 121, 54, 16))
        self.label_9.setObjectName("label_9")
        self.txt_login = QtWidgets.QLineEdit(emcform)
        self.txt_login.setGeometry(QtCore.QRect(270, 121, 40, 20))
        self.txt_login.setReadOnly(True)
        self.txt_login.setObjectName("txt_login")
        self.rb_emmc = QtWidgets.QRadioButton(emcform)
        self.rb_emmc.setGeometry(QtCore.QRect(100, 43, 50, 16))
        self.rb_emmc.setObjectName("rb_emmc")
        self.rb_gf = QtWidgets.QRadioButton(emcform)
        self.rb_gf.setGeometry(QtCore.QRect(100, 69, 50, 16))
        self.rb_gf.setObjectName("rb_gf")
        self.rb_e2r = QtWidgets.QRadioButton(emcform)
        self.rb_e2r.setGeometry(QtCore.QRect(100, 95, 50, 16))
        self.rb_e2r.setObjectName("rb_e2r")
        self.rb_c1 = QtWidgets.QRadioButton(emcform)
        self.rb_c1.setGeometry(QtCore.QRect(100, 147, 50, 16))
        self.rb_c1.setObjectName("rb_c1")
        self.rb_c0 = QtWidgets.QRadioButton(emcform)
        self.rb_c0.setGeometry(QtCore.QRect(100, 121, 50, 16))
        self.rb_c0.setObjectName("rb_c0")
        self.rb_login = QtWidgets.QRadioButton(emcform)
        self.rb_login.setGeometry(QtCore.QRect(320, 123, 50, 16))
        self.rb_login.setObjectName("rb_login")
        self.rb_l99m = QtWidgets.QRadioButton(emcform)
        self.rb_l99m.setGeometry(QtCore.QRect(320, 149, 50, 16))
        self.rb_l99m.setObjectName("rb_l99m")
        self.rb_c2 = QtWidgets.QRadioButton(emcform)
        self.rb_c2.setGeometry(QtCore.QRect(320, 71, 50, 16))
        self.rb_c2.setObjectName("rb_c2")
        self.rb_ec20 = QtWidgets.QRadioButton(emcform)
        self.rb_ec20.setGeometry(QtCore.QRect(320, 97, 50, 16))
        self.rb_ec20.setObjectName("rb_ec20")
        self.label_11 = QtWidgets.QLabel(emcform)
        self.label_11.setGeometry(QtCore.QRect(2, 205, 54, 16))
        self.label_11.setObjectName("label_11")
        self.rb_port = QtWidgets.QRadioButton(emcform)
        self.rb_port.setGeometry(QtCore.QRect(100, 205, 50, 16))
        self.rb_port.setObjectName("rb_port")
        self.txt_port = QtWidgets.QLineEdit(emcform)
        self.txt_port.setGeometry(QtCore.QRect(53, 205, 40, 20))
        self.txt_port.setReadOnly(True)
        self.txt_port.setObjectName("txt_port")
        self.layoutWidget = QtWidgets.QWidget(emcform)
        self.layoutWidget.setGeometry(QtCore.QRect(4, 180, 385, 18))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cb_fchrg = QtWidgets.QCheckBox(self.layoutWidget)
        self.cb_fchrg.setObjectName("cb_fchrg")
        self.horizontalLayout.addWidget(self.cb_fchrg)
        self.cb_chrg = QtWidgets.QCheckBox(self.layoutWidget)
        self.cb_chrg.setObjectName("cb_chrg")
        self.horizontalLayout.addWidget(self.cb_chrg)
        self.cb_ecall = QtWidgets.QCheckBox(self.layoutWidget)
        self.cb_ecall.setObjectName("cb_ecall")
        self.horizontalLayout.addWidget(self.cb_ecall)
        self.cb_bcall = QtWidgets.QCheckBox(self.layoutWidget)
        self.cb_bcall.setObjectName("cb_bcall")
        self.horizontalLayout.addWidget(self.cb_bcall)
        self.cb_icall = QtWidgets.QCheckBox(self.layoutWidget)
        self.cb_icall.setObjectName("cb_icall")
        self.horizontalLayout.addWidget(self.cb_icall)
        self.cb_sbs = QtWidgets.QCheckBox(self.layoutWidget)
        self.cb_sbs.setObjectName("cb_sbs")
        self.horizontalLayout.addWidget(self.cb_sbs)
        self.cb_kl15 = QtWidgets.QCheckBox(self.layoutWidget)
        self.cb_kl15.setObjectName("cb_kl15")
        self.horizontalLayout.addWidget(self.cb_kl15)
        self.btn_clear = QtWidgets.QPushButton(emcform)
        self.btn_clear.setGeometry(QtCore.QRect(290, 201, 60, 23))
        self.btn_clear.setObjectName("btn_clear")

        self.retranslateUi(emcform)
        QtCore.QMetaObject.connectSlotsByName(emcform)

    def retranslateUi(self, emcform):
        _translate = QtCore.QCoreApplication.translate
        emcform.setWindowTitle(_translate("emcform", "EMC测试上位机"))
        emcform.setFixedSize(emcform.width(), emcform.height())
        self.btn_serch.setText(_translate("emcform", "搜索"))
        self.btn_open.setText(_translate("emcform", "打开"))
        self.btn_send.setText(_translate("emcform", "发送"))
        self.btn_sql.setText(_translate("emcform", "查看"))
        self.label.setText(_translate("emcform", "EMMC"))
        self.btn_emmc.setText(_translate("emcform", "emmc"))
        self.label_2.setText(_translate("emcform", "功放"))
        self.label_3.setText(_translate("emcform", "EPPROM"))
        self.label_4.setText(_translate("emcform", "CAN0"))
        self.label_5.setText(_translate("emcform", "CAN1"))
        self.btn_gf.setText(_translate("emcform", "功放"))
        self.btn_epprom.setText(_translate("emcform", "epprom"))
        self.btn_c0.setText(_translate("emcform", "CAN0"))
        self.btn_can1.setText(_translate("emcform", "CAN1"))
        self.btn_can2.setText(_translate("emcform", "CAN2"))
        self.btn_dtu.setText(_translate("emcform", "DTU"))
        self.btn_login.setText(_translate("emcform", "login"))
        self.btn_l99m.setText(_translate("emcform", "L99M"))
        self.btn_port.setText(_translate("emcform", "PORT"))
        self.btn_fill.setText(_translate("emcform", "充电"))
        self.label_8.setText(_translate("emcform", "EC20"))
        self.label_10.setText(_translate("emcform", "L99M"))
        self.label_7.setText(_translate("emcform", "CAN2"))
        self.label_6.setText(_translate("emcform", "MCU"))
        self.label_9.setText(_translate("emcform", "LOGIN"))
        self.rb_emmc.setText(_translate("emcform", "异常"))
        self.rb_gf.setText(_translate("emcform", "异常"))
        self.rb_e2r.setText(_translate("emcform", "异常"))
        self.rb_c1.setText(_translate("emcform", "异常"))
        self.rb_c0.setText(_translate("emcform", "异常"))
        self.rb_login.setText(_translate("emcform", "异常"))
        self.rb_l99m.setText(_translate("emcform", "异常"))
        self.rb_c2.setText(_translate("emcform", "异常"))
        self.rb_ec20.setText(_translate("emcform", "异常"))
        self.label_11.setText(_translate("emcform", "端口"))
        self.rb_port.setText(_translate("emcform", "按键"))
        self.cb_fchrg.setText(_translate("emcform", "fchrg"))
        self.cb_chrg.setText(_translate("emcform", "chrg"))
        self.cb_ecall.setText(_translate("emcform", "ecall"))
        self.cb_bcall.setText(_translate("emcform", "bcall"))
        self.cb_icall.setText(_translate("emcform", "icall"))
        self.cb_sbs.setText(_translate("emcform", "sbs"))
        self.cb_kl15.setText(_translate("emcform", "kl15"))
        self.btn_clear.setText(_translate("emcform", "清除"))

